ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Athletes & Entertainers';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Bootstrapped Companies';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Business Executives';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Business Owners/Entrepreneurs';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Content Creators';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Cryptocurrency Investors';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Divorced Individuals';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Enterprise Companies ($50M+)';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Generational Wealth Transfer';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Growing Companies ($1M-$10M)';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Multi-generational Families';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Multi-state Returns';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Pre-Retirees (5-10 years out)';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Pre-revenue Startups';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Private Equity-Backed Companies';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Professors & Educators';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Retirees';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'SMB Owners';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'VC Backed Startups';
ALTER TYPE public.client_specialty_type ADD VALUE IF NOT EXISTS 'Young Professionals';