// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqtvpeuhjgqcjbdozzuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxdHZwZXVoamdxY2piZG96enV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjMyMDYsImV4cCI6MjA2MzA5OTIwNn0.XRIJNsN79oL0i1gYr9LnWh_WM_UpEkkpJBoinVYeaes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);